draft of batch design
odahu/odahu-docs pull request #103
Opened 2021-02-17 11:25 UTC by vlad-tokarev

2021-02-18 11:48 UTC, BPylypenko requested changes

2021-02-18 11:48 UTC, BPylypenko commented on source/architecture_batch.md
> +4. Triggers that allow to run this job
small grammar fixes
``` suggestion
A user wants to run workloads using a trigger (cron, webhook, cloud events) that makes predictions on a dataset using ML Model.

This dataset could have a relatively large size and the use of blocking web API does not fit this use case perfectly.

So we should provide an async API that provides a way to specify: 

1. Where input data is located (object storage link: s3, gcs, azure, etc)
2. Where the model is located (object storage link: s3, gcs, azure, etc) OR maybe some specific ML Registry such as MLFlow registry
3. Where output data should be uploaded (object storage link: s3, gcs, azure, etc)
4. Triggers that allow running this job.
```

2021-02-18 11:48 UTC, BPylypenko commented on source/architecture_batch.md
> +- Spec.inputPath must be a file in remote storage (not directory) and be one of next two options:
```suggestion
- Spec.inputPath must be a file in remote storage (not a directory) and be one of the next two options:
```

2021-02-18 11:48 UTC, BPylypenko commented on source/architecture_batch.md
> +  - option 2: .tar.gz file that contain a compressed bundle of json files the same format as json from option 1
```suggestion
  - option 2: .tar.gz file that contains a compressed bundle of json files in the same format as json from option 1
```

2021-02-18 11:48 UTC, BPylypenko commented on source/architecture_batch.md
> +- Spec.outputPath must be a file in remote storage (not directory) and be one of next two options:
```suggestion
- Spec.outputPath must be a file in remote storage (not a directory) and be one of the next two options:
```

2021-02-18 11:48 UTC, BPylypenko commented on source/architecture_batch.md
> +  - option 2: .tar.gz file that contain a compressed bundle of json files the same format as json from option 1
```suggestion
  - option 2: .tar.gz file that contain a compressed bundle of json files in the same format as json from option 1
```

2021-02-18 11:48 UTC, BPylypenko commented on source/architecture_batch.md
> +      enabled: true
We plan, for now, to add only `webhook` triggers or, maybe, it worth creating a separate entity for triggers? To have the possibility update only trigger URI or type of trigger?

2021-02-24 09:01 UTC, keshamin approved these changes

2021-02-26 09:43 UTC, BPylypenko approved these changes

2021-03-02 13:59 UTC, easokol approved these changes

2021-03-10 10:32 UTC, karbyshevds approved these changes

2021-03-15 13:34 UTC, keshamin approved these changes

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +This section describes API and protocols related to Batch inference using ODAHU
```suggestion
This section describes API and protocols related to Batch inference using ODAHU.
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +WEB API but other mechanisms.
```suggestion
ODAHU Batch Inference feature allows user to get inferences using ML model for large datasets that are delivered asyncronously, not via
HTTP API, but through other mechanisms.
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +For the future we consider to add ability to process data directly from Kafka topic and other async data sources.
```suggestion
In future we consider to add ability to process data directly from Kafka topic and other async data sources.
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +When user trained a model then he should build and image with code that follows `Predictor code protocol`_ and register
```suggestion
When a user trains a model then they should build an image with code that follows `Predictor code protocol`_ and register
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +``InferenceJob`` describes forecast process that was triggered by on of the triggers of ``InferenceService``.
```suggestion
``InferenceJob`` describes forecast process that was triggered by one of the triggers in ``InferenceService``.
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +below. Be default webhook trigger is enabled. Note, that currently its the only one way to trigger jobs.
```suggestion
below. By default webhook trigger is enabled. Note, that currently its the only one way to trigger jobs.
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +ODAHU Platform launches docker image that provided by user as ``[].spec.image`` (InferenceService_) and guaranties the
```suggestion
ODAHU Platform launches docker image provided by user as ``[].spec.image`` (InferenceService_) and guarantees the
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +InferenceService represents next required entities:
```suggestion
InferenceService represents the following required entities:
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +Currently Batch Inference supports next ways to delivery data for forecasting:
```suggestion
Currently Batch Inference supports the following ways to delivery data for forecasting:
```

2021-03-15 13:34 UTC, keshamin commented on source/ref_batch.rst
> +- Command and Arguments that describe how to execute image
Isn't it also responsible for input/output data location?

2021-03-17 06:05 UTC, easokol approved these changes

2021-03-17 07:58 UTC, karbyshevds approved these changes

2021-03-17 09:25 UTC, merged