1.4.0 changelog
odahu/odahu-docs pull request #105
Opened 2021-02-26 00:39 UTC by karbyshevds

2021-02-26 09:22 UTC, vlad-tokarev approved these changes

2021-02-26 11:56 UTC, BPylypenko requested changes

2021-02-26 11:56 UTC, BPylypenko commented on source/ref_changelog.rst
> +    * Default branch is now taken for VCS connection is not provided by user (`#148 <https://github.com/odahu/odahu-flow/issues/148>`_).
```suggestion
    * Default branch is now taken for VCS connection if it's not provided by user (`#148 <https://github.com/odahu/odahu-flow/issues/148>`_).
```

2021-02-27 17:57 UTC, easokol approved these changes

2021-02-27 17:59 UTC, merged