1.6.0 changelog
odahu/odahu-docs pull request #118
Opened 2021-09-02 20:07 UTC by karbyshevds

2021-09-06 09:36 UTC, BPylypenko requested changes

2021-09-06 09:36 UTC, BPylypenko commented on source/ref_changelog.rst
> +    * Model feedback & Triton model logs are now stored without model name/versoon (`#607 <https://github.com/odahu/odahu-flow/issues/607>`_,).
```suggestion
    * Model feedback & Triton model logs are now stored with model name/version (`#607 <https://github.com/odahu/odahu-flow/issues/607>`_,).
```

2021-09-08 08:56 UTC, BPylypenko approved these changes

2021-09-15 11:42 UTC, lev-titov approved these changes

2021-09-15 11:49 UTC, merged