[#5] How to use yaml/json files to describe payloads in airflow DAGs
odahu/odahu-docs pull request #19
Opened 2019-12-03 10:35 UTC by vlad-tokarev

Docs for https://github.com/odahu/odahu-airflow-plugin/issues/5

2019-12-03 10:45 UTC, mcdoker18 requested changes

2019-12-03 10:45 UTC, mcdoker18 commented on source/int_airflow.rst
> +But if you did some RnD work with Odahu-flow previously it's likely that you already have yaml/json files that
```suggestion
But if you did some RnD work with Odahu-flow previously, it's likely that you already have yaml/json files that
```

2019-12-03 10:45 UTC, mcdoker18 commented on source/int_airflow.rst
> +Actually this is payload that describes resource that will be created at Odahu-flow cluster. You should describe
```suggestion
Actually, this is payload that describes a resource that will be created at Odahu-flow cluster. You should describe
```

2019-12-03 10:45 UTC, mcdoker18 commented on source/int_airflow.rst
> +
Please, provide an example, how to push a dag with yaml files to a GCP Composer.

2019-12-08 13:32 UTC, mcdoker18 approved these changes

2019-12-09 12:21 UTC, maxkochubey approved these changes

2019-12-10 13:42 UTC, merged