[#1080] Airflow integration reference
odahu/odahu-docs pull request #2
Opened 2019-11-11 14:40 UTC by vlad-tokarev

2019-11-11 16:00 UTC, maxkochubey approved these changes

2019-11-12 15:21 UTC, jasonnerothin commented on source/int_airflow.rst
> +Legion provide a set of custom operators to give you the ability to interact with legion cluster using `Apache Airflow <https://airflow.apache.org/>`_
Legion provides a set of custom operators that allow you to interact with a Legion cluster using

2019-11-12 15:22 UTC, jasonnerothin commented on source/int_airflow.rst
> +Airflow plugin should be authorized at Legion. Authorization is implemented using regular `Airflow Connections <https://airflow.apache.org/concepts.html#connections>`_
The Airflow plugin should be authorized by Legion.

2019-11-12 15:25 UTC, jasonnerothin commented on source/int_airflow.rst
> +    connection. Because Legion uses OpenID authorization under the hood lots of extras are regular OpenID (OAuth 2.0)
Because Legion uses OpenID authorization, additional OpenID/OAuth 2.0 parameters may be supplied here.

2019-11-12 15:25 UTC, jasonnerothin commented on source/int_airflow.rst
> +This chapter describes custom operators that are provided by Legion.
This chapter describes the custom operators provided by Legion.

2019-11-12 15:27 UTC, jasonnerothin requested changes
Good work. Please update with the recommended changes.

2019-11-13 08:18 UTC, merged