Updated dev_testing.md
odahu/odahu-docs pull request #58
Opened 2020-02-21 11:28 UTC by BPylypenko

2020-02-21 11:54 UTC, maxkochubey requested changes

2020-02-21 11:54 UTC, maxkochubey commented on source/dev_testing.md
> +It's expected that you are using POSIX operating system and have installed Python 3.6.9+ and pip.
```suggestion
It's expected that you are using POSIX-compliant operating system and have installed Python 3.6.9+ and pip.
```

2020-02-21 11:54 UTC, maxkochubey commented on source/dev_testing.md
> +   DOCKER_REGISTRY=gcr.io/or2-msq-epmd-legn-t1iylu/odahu
```suggestion
   DOCKER_REGISTRY=gcr.io/or2-msq-myprojectid-t1iylu/odahu
```

2020-02-21 12:28 UTC, mcdoker18 approved these changes

2020-02-21 12:50 UTC, mcdoker18 approved these changes

2020-02-25 07:29 UTC, maxkochubey approved these changes

2020-02-25 08:54 UTC, merged