added info about local odahuflow
odahu/odahu-docs pull request #66
Opened 2020-03-17 08:05 UTC by BPylypenko

* added prerequisites for local training and packaging in local Quicstart page.
* added a mention about local command in Model Trainings and Model Packagers pages.

2020-03-17 09:24 UTC, mcdoker18 requested changes

2020-03-17 09:24 UTC, mcdoker18 commented on source/tutorials_local_wine.rst
> +- Linux based system with bash (at least version 4)
It's wrong. Please remove it.

2020-03-17 09:24 UTC, mcdoker18 commented on source/tutorials_local_wine.rst
> +- Python 3.6 or later
This is requirement of `odahuflowctl`, so please remove the line.

2020-03-17 09:24 UTC, mcdoker18 commented on source/ref_trainings.rst
> +    odahuflowctl local train run --help
Please, provide a real example of run command

2020-03-17 09:24 UTC, mcdoker18 commented on source/ref_packagers.rst
> +    odahuflowctl local pack run --help
Please, provide a real example of run command

2020-03-17 20:00 UTC, mcdoker18 approved these changes

2020-03-18 13:40 UTC, maxkochubey approved these changes

2020-03-18 13:51 UTC, vlad-tokarev approved these changes

2020-03-18 14:01 UTC, merged