#feat Add UML Sequence Diagram of successfully authorized API request
odahu/odahu-docs pull request #67
Opened 2020-03-26 16:11 UTC by vlad-tokarev

feat Add UML Sequence Diagram of the successfully authorized API request

![image](https://user-images.githubusercontent.com/30889080/77669288-9f33be00-6f95-11ea-8696-16cfb54e74bb.png)

2020-03-26 17:30 UTC, BPylypenko commented on source/gen_security.rst
>  4. If request if permitted by OpenPolicyAgent_ it is sent to upstream (ODAHU API)
```suggestion
4. If a request is permitted by OpenPolicyAgent_, it is sent to upstream (ODAHU API)
```

2020-03-26 17:30 UTC, BPylypenko commented on source/img/odahu_security_sequence.source
> +# this source code can be redered to UML diagram on https://www.websequencediagrams.com/
```suggestion
# this source code can be rendered to UML diagram on https://www.websequencediagrams.com/
```
I suppose that was meant.

2020-03-26 20:09 UTC, maxkochubey approved these changes

2020-03-26 20:11 UTC, maxkochubey commented
Please, replace "NGNIX" to "Nginx" on the picture :)

2020-03-26 20:12 UTC, maxkochubey commented on source/img/odahu_security_sequence.source
> +Client -> NGNIX: API request + JWT in cookie
```suggestion
Client -> NGINX: API request + JWT in cookie
```

2020-03-27 07:16 UTC, kirillmakhonin reviewed
Can we replace web based uml generators to something that we can integrate into docs building process? E.g. doT or graphviz or plantuml.

2020-03-27 09:30 UTC, vlad-tokarev commented
> Can we replace web based uml generators to something that we can integrate into docs building process? E.g. doT or graphviz or plantuml.

plantuml looks perfect, I haven't found this tool when try to search offline opensource solutions. Thanks. I will try to use it

2020-06-04 09:19 UTC, BPylypenko approved these changes

2020-06-16 00:14 UTC, karbyshevds requested changes

2020-06-16 00:14 UTC, karbyshevds commented on source/img/odahu_security_sequence.source
> +NGNIX -> OAuth2proxy: authenticated?
```suggestion
NGINX -> OAuth2proxy: authenticated?
```

2020-06-16 00:14 UTC, karbyshevds commented on source/img/odahu_security_sequence.source
> +NGNIX -> envoy sidecar: API request + JWT in header
```suggestion
NGINX -> envoy sidecar: API request + JWT in header
```

2020-09-03 03:57 UTC, dsuslov approved these changes

2020-09-03 07:29 UTC, karbyshevds approved these changes

2020-09-03 11:29 UTC, karbyshevds approved these changes

2020-09-03 11:53 UTC, keshamin approved these changes

2020-09-03 11:55 UTC, merged