Changelog: odahuflowctl local pack run changes info
odahu/odahu-docs pull request #97
Opened 2020-10-30 10:48 UTC by vlad-tokarev

2020-11-03 10:24 UTC, keshamin commented
@vlad-tokarev Do you want to merge all changes at once in this single PR when it's time to release 1.4 or to merge the changes incrementally?

2020-11-03 11:56 UTC, BPylypenko requested changes

2020-11-03 11:56 UTC, BPylypenko commented on source/ref_changelog.rst
> +    * We added ``odahuflowctl local pack run`` command's new option ``--disable-target`` that allows you disable targets
```suggestion
    * We added ``--disable-target`` option for ``odahuflowctl local pack run`` command that allows you disable targets
```
Maybe changes stress a little but, for me, it's easier to read.

2020-11-03 11:56 UTC, BPylypenko commented on source/ref_changelog.rst
> +    * ``odahuflowctl local pack run`` behavior that implicitly disable all targets by default is deprecated.
```suggestion
    * ``odahuflowctl local pack run`` behavior that implicitly disables all targets by default is deprecated.
```

2020-11-03 12:00 UTC, vlad-tokarev commented
> @vlad-tokarev Do you want to merge all changes at once in this single PR when it's time to release 1.4 or to merge the changes incrementally?

I suggest merging the changes incrementally as soon as the related feature is merged

2020-11-03 12:11 UTC, BPylypenko approved these changes

2020-11-03 16:26 UTC, keshamin approved these changes

2020-11-06 06:16 UTC, easokol approved these changes

2020-11-06 11:14 UTC, karbyshevds approved these changes

2020-12-24 09:44 UTC, merged